import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

// Indian Languages Translations
const translations = {
  en: {
    name: 'English',
    // Navigation
    home: 'Home',
    leaderboard: 'Leaderboard',
    report: 'Report',
    track: 'Track',
    donation: 'Donation',
    profile: 'Profile',
    chatbot: 'Chat',
    // Common
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    loading: 'Loading...',
    success: 'Success!',
    error: 'Error',
    // Home
    welcomeTitle: 'Report & Track Civic Issues',
    welcomeSubtitle: 'Make your community better',
    // Report
    reportProblem: 'Report a Problem',
    category: 'Category',
    description: 'Description',
    location: 'Location',
    getLocation: 'Get Location',
    takePhoto: 'Take Photo',
    submitReport: 'Submit Report',
    // Track
    trackReports: 'Track Reports',
    status: 'Status',
    submitted: 'Submitted',
    inProgress: 'In Progress',
    done: 'Done',
    // Leaderboard
    topContributors: 'Top Contributors',
    points: 'Points',
    rank: 'Rank',
    // Profile
    editProfile: 'Edit Profile',
    displayName: 'Display Name',
    email: 'Email',
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    logout: 'Logout',
    changePhoto: 'Change Photo',
    // Donation
    donateItems: 'Donate Items',
    availableItems: 'Available Items',
    // Categories
    garbageSpaces: 'Garbage on Open Spaces',
    roadDamage: 'Road Damage',
    drainageIssues: 'Drainage Issues',
    streetLight: 'Street Light Problem',
    waterLeakage: 'Water Leakage',
    pothole: 'Pothole',
    accidentSpot: 'Accident Spot',
    brokenBench: 'Broken Bench',
    parkIssues: 'Park Issues',
    other: 'Other'
  },
  hi: {
    name: 'हिंदी',
    // Navigation
    home: 'होम',
    leaderboard: 'लीडरबोर्ड',
    report: 'रिपोर्ट',
    track: 'ट्रैक',
    donation: 'दान',
    profile: 'प्रोफ़ाइल',
    chatbot: 'चैट',
    // Common
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    loading: 'लोड हो रहा है...',
    success: 'सफल!',
    error: 'त्रुटि',
    // Home
    welcomeTitle: 'नागरिक समस्याओं की रिपोर्ट करें और ट्रैक करें',
    welcomeSubtitle: 'अपने समुदाय को बेहतर बनाएं',
    // Report
    reportProblem: 'समस्या की रिपोर्ट करें',
    category: 'श्रेणी',
    description: 'विवरण',
    location: 'स्थान',
    getLocation: 'स्थान प्राप्त करें',
    takePhoto: 'फोटो लें',
    submitReport: 'रिपोर्ट जमा करें',
    // Track
    trackReports: 'रिपोर्ट ट्रैक करें',
    status: 'स्थिति',
    submitted: 'जमा किया गया',
    inProgress: 'प्रगति में',
    done: 'पूर्ण',
    // Leaderboard
    topContributors: 'शीर्ष योगदानकर्ता',
    points: 'अंक',
    rank: 'रैंक',
    // Profile
    editProfile: 'प्रोफ़ाइल संपादित करें',
    displayName: 'प्रदर्शन नाम',
    email: 'ईमेल',
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    logout: 'लॉग आउट',
    changePhoto: 'फोटो बदलें',
    // Donation
    donateItems: 'वस्तुएं दान करें',
    availableItems: 'उपलब्ध वस्तुएं',
    // Categories
    garbageSpaces: 'खुली जगहों पर कचरा',
    roadDamage: 'सड़क क्षति',
    drainageIssues: 'जल निकासी समस्याएं',
    streetLight: 'स्ट्रीट लाइट समस्या',
    waterLeakage: 'पानी का रिसाव',
    pothole: 'गड्ढा',
    accidentSpot: 'दुर्घटना स्थल',
    brokenBench: 'टूटी हुई बेंच',
    parkIssues: 'पार्क समस्याएं',
    other: 'अन्य'
  },
  mr: {
    name: 'मराठी',
    home: 'होम',
    leaderboard: 'लीडरबोर्ड',
    report: 'अहवाल',
    track: 'ट्रॅक',
    donation: 'देणगी',
    profile: 'प्रोफाइल',
    chatbot: 'चॅट',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    loading: 'लोड होत आहे...',
    success: 'यश!',
    error: 'त्रुटी',
    welcomeTitle: 'नागरी समस्या नोंदवा आणि ट्रॅक करा',
    welcomeSubtitle: 'तुमचा समुदाय चांगला बनवा',
    reportProblem: 'समस्या नोंदवा',
    category: 'श्रेणी',
    description: 'वर्णन',
    location: 'स्थान',
    getLocation: 'स्थान मिळवा',
    takePhoto: 'फोटो घ्या',
    submitReport: 'अहवाल सबमिट करा',
    trackReports: 'अहवाल ट्रॅक करा',
    status: 'स्थिती',
    submitted: 'सबमिट केले',
    inProgress: 'प्रगतीपथावर',
    done: 'पूर्ण',
    topContributors: 'शीर्ष योगदानकर्ते',
    points: 'गुण',
    rank: 'रँक',
    editProfile: 'प्रोफाइल संपादित करा',
    displayName: 'प्रदर्शन नाव',
    email: 'ईमेल',
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    logout: 'लॉग आउट',
    changePhoto: 'फोटो बदला',
    donateItems: 'वस्तू दान करा',
    availableItems: 'उपलब्ध वस्तू',
    garbageSpaces: 'मोकळ्या जागेवर कचरा',
    roadDamage: 'रस्ता खराब',
    drainageIssues: 'ड्रेनेज समस्या',
    streetLight: 'रस्त्यावरील दिवा समस्या',
    waterLeakage: 'पाणी गळती',
    pothole: 'खड्डा',
    accidentSpot: 'अपघात स्थळ',
    brokenBench: 'तुटलेली बाक',
    parkIssues: 'उद्यान समस्या',
    other: 'इतर'
  },
  ta: {
    name: 'தமிழ்',
    home: 'முகப்பு',
    leaderboard: 'லீடர்போர்டு',
    report: 'புகார்',
    track: 'தடம்',
    donation: 'நன்கொடை',
    profile: 'சுயவிவரம்',
    chatbot: 'அரட்டை',
    submit: 'சமர்ப்பி',
    cancel: 'ரத்து',
    save: 'சேமி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    loading: 'ஏற்றுகிறது...',
    success: 'வெற்றி!',
    error: 'பிழை',
    welcomeTitle: 'குடிமை சிக்கல்களைப் புகாரளிக்கவும் கண்காணிக்கவும்',
    welcomeSubtitle: 'உங்கள் சமூகத்தை சிறப்பாக்குங்கள்',
    reportProblem: 'சிக்கலைப் புகாரளி',
    category: 'வகை',
    description: 'விவரம்',
    location: 'இடம்',
    getLocation: 'இடத்தைப் பெறு',
    takePhoto: 'புகைப்படம் எடு',
    submitReport: 'புகாரை சமர்ப்பி',
    trackReports: 'புகார்களைக் கண்காணி',
    status: 'நிலை',
    submitted: 'சமர்ப்பிக்கப்பட்டது',
    inProgress: 'செயல்பாட்டில்',
    done: 'முடிந்தது',
    topContributors: 'சிறந்த பங்களிப்பாளர்கள்',
    points: 'புள்ளிகள்',
    rank: 'தரவரிசை',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    displayName: 'காட்சி பெயர்',
    email: 'மின்னஞ்சல்',
    language: 'மொழி',
    darkMode: 'இருண்ட பயன்முறை',
    lightMode: 'வெளிச்ச பயன்முறை',
    logout: 'வெளியேறு',
    changePhoto: 'புகைப்படத்தை மாற்று',
    donateItems: 'பொருட்களை நன்கொடையளி',
    availableItems: 'கிடைக்கும் பொருட்கள்',
    garbageSpaces: 'திறந்த இடங்களில் குப்பை',
    roadDamage: 'சாலை சேதம்',
    drainageIssues: 'வடிகால் சிக்கல்கள்',
    streetLight: 'தெரு விளக்கு பிரச்சனை',
    waterLeakage: 'நீர் கசிவு',
    pothole: 'குழி',
    accidentSpot: 'விபத்து இடம்',
    brokenBench: 'உடைந்த பெஞ்ச்',
    parkIssues: 'பூங்கா சிக்கல்கள்',
    other: 'மற்றவை'
  },
  te: {
    name: 'తెలుగు',
    home: 'హోమ్',
    leaderboard: 'లీడర్‌బోర్డ్',
    report: 'నివేదిక',
    track: 'ట్రాక్',
    donation: 'విరాళం',
    profile: 'ప్రొఫైల్',
    chatbot: 'చాట్',
    submit: 'సమర్పించు',
    cancel: 'రద్దు',
    save: 'సేవ్',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    loading: 'లోడ్ అవుతోంది...',
    success: 'విజయం!',
    error: 'లోపం',
    welcomeTitle: 'పౌర సమస్యలను నివేదించండి & ట్రాక్ చేయండి',
    welcomeSubtitle: 'మీ సమాజాన్ని మెరుగ్గా చేయండి',
    reportProblem: 'సమస్యను నివేదించు',
    category: 'వర్గం',
    description: 'వివరణ',
    location: 'స్థానం',
    getLocation: 'స్థానం పొందండి',
    takePhoto: 'ఫోటో తీయండి',
    submitReport: 'నివేదిక సమర్పించు',
    trackReports: 'నివేదికలను ట్రాక్ చేయి',
    status: 'స్థితి',
    submitted: 'సమర్పించబడింది',
    inProgress: 'ప్రగతిలో ఉంది',
    done: 'పూర్తయింది',
    topContributors: 'అగ్ర సహకారులు',
    points: 'పాయింట్లు',
    rank: 'ర్యాంక్',
    editProfile: 'ప్రొఫైల్ సవరించు',
    displayName: 'ప్రదర్శన పేరు',
    email: 'ఇమెయిల్',
    language: 'భాష',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    logout: 'లాగ్ అవుట్',
    changePhoto: 'ఫోటో మార్చు',
    donateItems: 'వస్తువులు విరాళం',
    availableItems: 'అందుబాటులో ఉన్న వస్తువులు',
    garbageSpaces: 'ఖాళీ ప్రదేశాలలో చెత్త',
    roadDamage: 'రోడ్డు నష్టం',
    drainageIssues: 'డ్రైనేజీ సమస్యలు',
    streetLight: 'వీధి దీపం సమస్య',
    waterLeakage: 'నీటి లీకేజీ',
    pothole: 'గొయ్యి',
    accidentSpot: 'ప్రమాద స్థలం',
    brokenBench: 'విరిగిన బెంచ్',
    parkIssues: 'పార్కు సమస్యలు',
    other: 'ఇతర'
  },
  bn: {
    name: 'বাংলা',
    home: 'হোম',
    leaderboard: 'লিডারবোর্ড',
    report: 'রিপোর্ট',
    track: 'ট্র্যাক',
    donation: 'দান',
    profile: 'প্রোফাইল',
    chatbot: 'চ্যাট',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    loading: 'লোড হচ্ছে...',
    success: 'সফল!',
    error: 'ত্রুটি',
    welcomeTitle: 'নাগরিক সমস্যা রিপোর্ট করুন এবং ট্র্যাক করুন',
    welcomeSubtitle: 'আপনার সম্প্রদায়কে উন্নত করুন',
    reportProblem: 'সমস্যা রিপোর্ট করুন',
    category: 'বিভাগ',
    description: 'বিবরণ',
    location: 'অবস্থান',
    getLocation: 'অবস্থান পান',
    takePhoto: 'ছবি তুলুন',
    submitReport: 'রিপোর্ট জমা দিন',
    trackReports: 'রিপোর্ট ট্র্যাক করুন',
    status: 'অবস্থা',
    submitted: 'জমা দেওয়া হয়েছে',
    inProgress: 'চলমান',
    done: 'সম্পন্ন',
    topContributors: 'শীর্ষ অবদানকারী',
    points: 'পয়েন্ট',
    rank: 'র‍্যাঙ্ক',
    editProfile: 'প্রোফাইল সম্পাদনা',
    displayName: 'প্রদর্শন নাম',
    email: 'ইমেল',
    language: 'ভাষা',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    logout: 'লগ আউট',
    changePhoto: 'ছবি পরিবর্তন',
    donateItems: 'জিনিস দান করুন',
    availableItems: 'উপলব্ধ আইটেম',
    garbageSpaces: 'খোলা জায়গায় আবর্জনা',
    roadDamage: 'রাস্তার ক্ষতি',
    drainageIssues: 'নিকাশী সমস্যা',
    streetLight: 'রাস্তার আলো সমস্যা',
    waterLeakage: 'জল লিকেজ',
    pothole: 'গর্ত',
    accidentSpot: 'দুর্ঘটনাস্থল',
    brokenBench: 'ভাঙা বেঞ্চ',
    parkIssues: 'পার্কের সমস্যা',
    other: 'অন্যান্য'
  },
  gu: {
    name: 'ગુજરાતી',
    home: 'હોમ',
    leaderboard: 'લીડરબોર્ડ',
    report: 'રિપોર્ટ',
    track: 'ટ્રેક',
    donation: 'દાન',
    profile: 'પ્રોફાઇલ',
    chatbot: 'ચેટ',
    submit: 'સબમિટ',
    cancel: 'રદ',
    save: 'સેવ',
    edit: 'સંપાદિત',
    delete: 'કાઢી નાખો',
    loading: 'લોડ થઈ રહ્યું છે...',
    success: 'સફળ!',
    error: 'ભૂલ',
    welcomeTitle: 'નાગરિક સમસ્યાઓ રિપોર્ટ કરો અને ટ્રેક કરો',
    welcomeSubtitle: 'તમારા સમુદાયને વધુ સારું બનાવો',
    reportProblem: 'સમસ્યાની જાણ કરો',
    category: 'શ્રેણી',
    description: 'વર્ણન',
    location: 'સ્થાન',
    getLocation: 'સ્થાન મેળવો',
    takePhoto: 'ફોટો લો',
    submitReport: 'રિપોર્ટ સબમિટ કરો',
    trackReports: 'રિપોર્ટ ટ્રેક કરો',
    status: 'સ્થિતિ',
    submitted: 'સબમિટ કર્યું',
    inProgress: 'પ્રગતિમાં',
    done: 'પૂર્ણ',
    topContributors: 'ટોચના યોગદાનકર્તાઓ',
    points: 'પોઈન્ટ્સ',
    rank: 'રેન્ક',
    editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    displayName: 'પ્રદર્શન નામ',
    email: 'ઈમેલ',
    language: 'ભાષા',
    darkMode: 'ડાર્ક મોડ',
    lightMode: 'લાઇટ મોડ',
    logout: 'લોગ આઉટ',
    changePhoto: 'ફોટો બદલો',
    donateItems: 'વસ્તુઓ દાન કરો',
    availableItems: 'ઉપલબ્ધ વસ્તુઓ',
    garbageSpaces: 'ખુલ્લી જગ્યાઓમાં કચરો',
    roadDamage: 'રસ્તાનું નુકસાન',
    drainageIssues: 'ડ્રેનેજ સમસ્યાઓ',
    streetLight: 'સ્ટ્રીટ લાઇટ સમસ્યા',
    waterLeakage: 'પાણીનું લિકેજ',
    pothole: 'ખાડો',
    accidentSpot: 'અકસ્માત સ્થળ',
    brokenBench: 'તૂટેલી બેન્ચ',
    parkIssues: 'પાર્કની સમસ્યાઓ',
    other: 'અન્ય'
  },
  kn: {
    name: 'ಕನ್ನಡ',
    home: 'ಮುಖಪುಟ',
    leaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    report: 'ವರದಿ',
    track: 'ಟ್ರ್ಯಾಕ್',
    donation: 'ದಾನ',
    profile: 'ಪ್ರೊಫೈಲ್',
    chatbot: 'ಚಾಟ್',
    submit: 'ಸಲ್ಲಿಸು',
    cancel: 'ರದ್ದು',
    save: 'ಉಳಿಸು',
    edit: 'ಸಂಪಾದಿಸು',
    delete: 'ಅಳಿಸು',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    success: 'ಯಶಸ್ವಿ!',
    error: 'ದೋಷ',
    welcomeTitle: 'ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    welcomeSubtitle: 'ನಿಮ್ಮ ಸಮುದಾಯವನ್ನು ಉತ್ತಮಗೊಳಿಸಿ',
    reportProblem: 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    category: 'ವರ್ಗ',
    description: 'ವಿವರಣೆ',
    location: 'ಸ್ಥಳ',
    getLocation: 'ಸ್ಥಳ ಪಡೆಯಿರಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    submitReport: 'ವರದಿ ಸಲ್ಲಿಸಿ',
    trackReports: 'ವರದಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    status: 'ಸ್ಥಿತಿ',
    submitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    done: 'ಮುಗಿದಿದೆ',
    topContributors: 'ಅಗ್ರ ಕೊಡುಗೆದಾರರು',
    points: 'ಅಂಕಗಳು',
    rank: 'ಶ್ರೇಣಿ',
    editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    language: 'ಭಾಷೆ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    changePhoto: 'ಫೋಟೋ ಬದಲಿಸಿ',
    donateItems: 'ವಸ್ತುಗಳನ್ನು ದಾನ ಮಾಡಿ',
    availableItems: 'ಲಭ್ಯವಿರುವ ವಸ್ತುಗಳು',
    garbageSpaces: 'ತೆರೆದ ಸ್ಥಳಗಳಲ್ಲಿ ಕಸ',
    roadDamage: 'ರಸ್ತೆ ಹಾನಿ',
    drainageIssues: 'ಚರಂಡಿ ಸಮಸ್ಯೆಗಳು',
    streetLight: 'ಬೀದಿ ದೀಪ ಸಮಸ್ಯೆ',
    waterLeakage: 'ನೀರಿನ ಸೋರಿಕೆ',
    pothole: 'ಹಳ್ಳ',
    accidentSpot: 'ಅಪಘಾತ ಸ್ಥಳ',
    brokenBench: 'ಮುರಿದ ಬೆಂಚ್',
    parkIssues: 'ಉದ್ಯಾನ ಸಮಸ್ಯೆಗಳು',
    other: 'ಇತರೆ'
  },
  pa: {
    name: 'ਪੰਜਾਬੀ',
    home: 'ਹੋਮ',
    leaderboard: 'ਲੀਡਰਬੋਰਡ',
    report: 'ਰਿਪੋਰਟ',
    track: 'ਟ੍ਰੈਕ',
    donation: 'ਦਾਨ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    chatbot: 'ਚੈਟ',
    submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੇਵ ਕਰੋ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    delete: 'ਮਿਟਾਓ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    success: 'ਸਫ਼ਲ!',
    error: 'ਗਲਤੀ',
    welcomeTitle: 'ਨਾਗਰਿਕ ਸਮੱਸਿਆਵਾਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਟ੍ਰੈਕ ਕਰੋ',
    welcomeSubtitle: 'ਆਪਣੇ ਭਾਈਚਾਰੇ ਨੂੰ ਬਿਹਤਰ ਬਣਾਓ',
    reportProblem: 'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    category: 'ਸ਼੍ਰੇਣੀ',
    description: 'ਵੇਰਵਾ',
    location: 'ਸਥਾਨ',
    getLocation: 'ਸਥਾਨ ਲਓ',
    takePhoto: 'ਫੋਟੋ ਲਓ',
    submitReport: 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ',
    trackReports: 'ਰਿਪੋਰਟਾਂ ਟ੍ਰੈਕ ਕਰੋ',
    status: 'ਸਥਿਤੀ',
    submitted: 'ਜਮ੍ਹਾਂ ਕੀਤਾ',
    inProgress: 'ਪ੍ਰਗਤੀ ਵਿੱਚ',
    done: 'ਪੂਰਾ',
    topContributors: 'ਚੋਟੀ ਦੇ ਯੋਗਦਾਨੀ',
    points: 'ਪੁਆਇੰਟ',
    rank: 'ਰੈਂਕ',
    editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
    displayName: 'ਡਿਸਪਲੇ ਨਾਮ',
    email: 'ਈਮੇਲ',
    language: 'ਭਾਸ਼ਾ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    lightMode: 'ਲਾਈਟ ਮੋਡ',
    logout: 'ਲੌਗ ਆਊਟ',
    changePhoto: 'ਫੋਟੋ ਬਦਲੋ',
    donateItems: 'ਚੀਜ਼ਾਂ ਦਾਨ ਕਰੋ',
    availableItems: 'ਉਪਲਬਧ ਚੀਜ਼ਾਂ',
    garbageSpaces: 'ਖੁੱਲ੍ਹੀਆਂ ਥਾਵਾਂ ਵਿੱਚ ਕੂੜਾ',
    roadDamage: 'ਸੜਕ ਦਾ ਨੁਕਸਾਨ',
    drainageIssues: 'ਡਰੇਨੇਜ ਸਮੱਸਿਆਵਾਂ',
    streetLight: 'ਸਟ੍ਰੀਟ ਲਾਈਟ ਸਮੱਸਿਆ',
    waterLeakage: 'ਪਾਣੀ ਦਾ ਲੀਕੇਜ',
    pothole: 'ਟੋਆ',
    accidentSpot: 'ਦੁਰਘਟਨਾ ਸਥਾਨ',
    brokenBench: 'ਟੁੱਟੀ ਬੈਂਚ',
    parkIssues: 'ਪਾਰਕ ਸਮੱਸਿਆਵਾਂ',
    other: 'ਹੋਰ'
  }
};

export const availableLanguages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' }
];

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const changeLanguage = (langCode) => {
    if (translations[langCode]) {
      setLanguage(langCode);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}
